/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/loading_girl/scene.gltf 
Author: OSCAR CREATIVO (https://sketchfab.com/oscar_creativo)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/girl-warrior-motorcycle-cyber-by-oscar-creativo-c27030b41da04de29b0ba78c486a9b31
Title: GIRL WARRIOR MOTORCYCLE CYBER BY Oscar Creativo
*/

import React, { useEffect, useState } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function BikeGirl(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('../../public/loading_girl/scene.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions , names} = useAnimations(animations, group)
  console.log(names)
  useEffect(()=>{
    actions[names[0]].reset().fadeIn(0.5).play()
  },[]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[Math.PI / 2, 0, 0]} scale={1.709}>
          <group name="4e39ebea221f4cb48d2365361ee76078fbx" rotation={[-Math.PI, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="CC3_Base_Plus_0">
                    <group name="Object_164">
                      <primitive object={nodes._rootJoint_1} />
                      <group name="Object_267" />
                      <group name="Object_269" />
                      <group name="Object_276" />
                      <group name="Object_278" />
                      <group name="Object_280" />
                      <group name="Object_282" />
                      <group name="Object_284" />
                      <group name="Object_286" />
                      <group name="Object_288" />
                      <group name="Object_293" />
                      <group name="Object_296" />
                      <group name="Object_299" />
                      <group name="Object_302" />
                      <skinnedMesh name="Object_268" geometry={nodes.Object_268.geometry} material={materials.Std_Tongue} skeleton={nodes.Object_268.skeleton} morphTargetDictionary={nodes.Object_268.morphTargetDictionary} morphTargetInfluences={nodes.Object_268.morphTargetInfluences} />
                      <skinnedMesh name="Object_270" geometry={nodes.Object_270.geometry} material={materials.Std_Skin_Head} skeleton={nodes.Object_270.skeleton} morphTargetDictionary={nodes.Object_270.morphTargetDictionary} morphTargetInfluences={nodes.Object_270.morphTargetInfluences} />
                      <skinnedMesh name="Object_271" geometry={nodes.Object_271.geometry} material={materials.Std_Skin_Body} skeleton={nodes.Object_271.skeleton} morphTargetDictionary={nodes.Object_271.morphTargetDictionary} morphTargetInfluences={nodes.Object_271.morphTargetInfluences} />
                      <skinnedMesh name="Object_272" geometry={nodes.Object_272.geometry} material={materials.Std_Skin_Arm} skeleton={nodes.Object_272.skeleton} morphTargetDictionary={nodes.Object_272.morphTargetDictionary} morphTargetInfluences={nodes.Object_272.morphTargetInfluences} />
                      <skinnedMesh name="Object_273" geometry={nodes.Object_273.geometry} material={materials.Std_Skin_Leg} skeleton={nodes.Object_273.skeleton} morphTargetDictionary={nodes.Object_273.morphTargetDictionary} morphTargetInfluences={nodes.Object_273.morphTargetInfluences} />
                      <skinnedMesh name="Object_274" geometry={nodes.Object_274.geometry} material={materials.Std_Nails} skeleton={nodes.Object_274.skeleton} morphTargetDictionary={nodes.Object_274.morphTargetDictionary} morphTargetInfluences={nodes.Object_274.morphTargetInfluences} />
                      <skinnedMesh name="Object_275" geometry={nodes.Object_275.geometry} material={materials.Std_Eyelash} skeleton={nodes.Object_275.skeleton} morphTargetDictionary={nodes.Object_275.morphTargetDictionary} morphTargetInfluences={nodes.Object_275.morphTargetInfluences} />
                      <skinnedMesh name="Object_289" geometry={nodes.Object_289.geometry} material={materials.Std_Eye_R} skeleton={nodes.Object_289.skeleton} morphTargetDictionary={nodes.Object_289.morphTargetDictionary} morphTargetInfluences={nodes.Object_289.morphTargetInfluences} />
                      <skinnedMesh name="Object_290" geometry={nodes.Object_290.geometry} material={materials.Std_Cornea_R} skeleton={nodes.Object_290.skeleton} morphTargetDictionary={nodes.Object_290.morphTargetDictionary} morphTargetInfluences={nodes.Object_290.morphTargetInfluences} />
                      <skinnedMesh name="Object_291" geometry={nodes.Object_291.geometry} material={materials.Std_Eye_L} skeleton={nodes.Object_291.skeleton} morphTargetDictionary={nodes.Object_291.morphTargetDictionary} morphTargetInfluences={nodes.Object_291.morphTargetInfluences} />
                      <skinnedMesh name="Object_292" geometry={nodes.Object_292.geometry} material={materials.Std_Cornea_L} skeleton={nodes.Object_292.skeleton} morphTargetDictionary={nodes.Object_292.morphTargetDictionary} morphTargetInfluences={nodes.Object_292.morphTargetInfluences} />
                      <skinnedMesh name="Object_294" geometry={nodes.Object_294.geometry} material={materials.Std_Upper_Teeth} skeleton={nodes.Object_294.skeleton} morphTargetDictionary={nodes.Object_294.morphTargetDictionary} morphTargetInfluences={nodes.Object_294.morphTargetInfluences} />
                      <skinnedMesh name="Object_295" geometry={nodes.Object_295.geometry} material={materials.Std_Lower_Teeth} skeleton={nodes.Object_295.skeleton} morphTargetDictionary={nodes.Object_295.morphTargetDictionary} morphTargetInfluences={nodes.Object_295.morphTargetInfluences} />
                      <skinnedMesh name="Object_297" geometry={nodes.Object_297.geometry} material={materials.Std_Tearline_R} skeleton={nodes.Object_297.skeleton} morphTargetDictionary={nodes.Object_297.morphTargetDictionary} morphTargetInfluences={nodes.Object_297.morphTargetInfluences} />
                      <skinnedMesh name="Object_298" geometry={nodes.Object_298.geometry} material={materials.Std_Tearline_L} skeleton={nodes.Object_298.skeleton} morphTargetDictionary={nodes.Object_298.morphTargetDictionary} morphTargetInfluences={nodes.Object_298.morphTargetInfluences} />
                      <skinnedMesh name="Object_300" geometry={nodes.Object_300.geometry} material={materials.Std_Eye_Occlusion_R} skeleton={nodes.Object_300.skeleton} morphTargetDictionary={nodes.Object_300.morphTargetDictionary} morphTargetInfluences={nodes.Object_300.morphTargetInfluences} />
                      <skinnedMesh name="Object_301" geometry={nodes.Object_301.geometry} material={materials.Std_Eye_Occlusion_L} skeleton={nodes.Object_301.skeleton} morphTargetDictionary={nodes.Object_301.morphTargetDictionary} morphTargetInfluences={nodes.Object_301.morphTargetInfluences} />
                      <skinnedMesh name="Object_277" geometry={nodes.Object_277.geometry} material={materials.MergedBake_Baked} skeleton={nodes.Object_277.skeleton} />
                      <skinnedMesh name="Object_279" geometry={nodes.Object_279.geometry} material={materials['5_body_0_3_0_0']} skeleton={nodes.Object_279.skeleton} />
                      <skinnedMesh name="Object_281" geometry={nodes.Object_281.geometry} material={materials['5_body_0_3_0_0_0']} skeleton={nodes.Object_281.skeleton} />
                      <skinnedMesh name="Object_283" geometry={nodes.Object_283.geometry} material={materials['5_body_0_3_0_0_1']} skeleton={nodes.Object_283.skeleton} />
                      <skinnedMesh name="Object_285" geometry={nodes.Object_285.geometry} material={materials['5_body_0_3_0_0_2']} skeleton={nodes.Object_285.skeleton} />
                      <skinnedMesh name="Object_287" geometry={nodes.Object_287.geometry} material={materials['5_body_0_3_0_0_001']} skeleton={nodes.Object_287.skeleton} />
                      <skinnedMesh name="Object_303" geometry={nodes.Object_303.geometry} material={materials.Hair_Transparency} skeleton={nodes.Object_303.skeleton} />
                      <skinnedMesh name="Object_304" geometry={nodes.Object_304.geometry} material={materials.HairBand_Transparency} skeleton={nodes.Object_304.skeleton} />
                    </group>
                  </group>
                  <group name="CC_Base_Tongue" />
                  <group name="CC_Base_Body" />
                  <group name="EYESLASHES" />
                  <group name="TRAJE" />
                  <group name="GLOVES" />
                  <group name="LEG" />
                  <group name="CORREA" />
                  <group name="SHOES" />
                  <group name="CC_Base_Eye" />
                  <group name="CC_Base_Teeth" />
                  <group name="CC_Base_TearLine" />
                  <group name="CC_Base_EyeOcclusion" />
                  <group name="HAIR" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../public/loading_girl/scene.gltf')
